name: deploy-payments

on:
  push:
    branches:
      - main
    paths:
      - 'payments/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && docker build -t connerkeating/payments .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push connerkeating/payments
      - uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{secrets.KUBE_CONFIG_DATA}}
        with:
          args: '"rollout restart deployment payments-depl"'
